apiVersion: batch/v1
kind: Job
metadata:
  name: jobi
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
        - image: ubuntu
          name: test
          command:
            - "sleep"
            - "60"
      restartPolicy: Never