apiVersion: batch/v1
kind: Job
metadata:
  name: job1
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
        - image: ubuntu
          command:
            - "sleep"
            - "120"
      restartPolicy: Never